### ISSUE TITLE
create a v1 of create account / login only

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#169]
- idea (for feedback and discussion) to create the ability to login via google only as a v1
- as a user I can click on the google sign-in link and it will "log me in" which shows and icon with a letter from my name in the corner, and then I can log out.

figma design: https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?type=design&node-id=3441-60395&t=mHm5CF3TVUJzU3FA-4

**Comment by rostyslavvnahornyi** [comment]
Hello @kfarr!
I want to do a little more and create a profile page, but there is a problem with pages. It is too difficult to create a new one, since the project was originally under one and now I am trying to do it.

Now it's ready: a modal authorization window via google, a connected firebase, a context for authorization and saving a token, a logout.

I want to try to squeeze and make a profile page, but here I need more time, do you mind?

**Comment by kfarr** [comment]
Hi Rosty, the most important thing about this request is the basic ability to login and testing if the firebase structure meets expectations and is able to be deployed. The profile page is a nice request, and we can do it immediately after, but I think it's important to pause and share the work first to make sure it's replicable (aka deployable by me) and going in the right direction (aka meets architecture expectations).

**Comment by kfarr** [comment]
this ticket is done although work continues on PR #202 

here is an example of other tickets to continue this work:
https://github.com/3DStreet/3dstreet-editor/issues/204
