### ISSUE TITLE
save / load with mapbox entity via cloud storage not working

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#257]
To reproduce:
* load feature-firebase-save-load branch with dev environment credentials
* open localhost:3333/index-mapbox.html
* login to 3dstreet cloud via google account by clicking on person icon in upper-right hand corner
* save scene to cloud, note the UUID upon redirect after saving
* re-open using https://dev-3dstreet.web.app/#/scenes/UUID.json or http://localhost:3333/#https://dev-3dstreet.web.app/#/scenes/UUID.json
* result: note that the mapbox plane does not appear correctly, however the entity does show up as expected in the left-hand scene graph (ie there is only 1 entity, not multiple) 

![image](https://github.com/3DStreet/3dstreet-editor/assets/470477/ab398404-eb30-4c50-8421-95c7ddbba249)

**Comment by Algorush** [comment]
https://github.com/3DStreet/3dstreet-editor/pull/283
I discovered for the second time that when saving JSON via the cloud, the order of some components of entities differs from JSON during normal saving. Because of this, similar problems sometimes arise. So in this PR I defined the order of applying components to an entity when loading from JSON
